### ISSUE TITLE
Lazy load your *.js files

### ISSUE THREAD

**Issue by indexzero** [samsonjs/batteries#2]
I like this library, so I wanted to lend some advice from other large libraries I've written. Right now you eagerly load all of the `*.js` files: https://github.com/samsonjs/batteries/blob/master/lib/index.js#L15

This can affect the load time of your library for someone who (for example) only wants to use `batteries.fs`. Here's a quick example of how I would suggest doing this:

``` js
  fs.readdirSync(__dirname).forEach(function (file) {
    file = file.replace('.js', '');
    if (file !== 'index') {
      module.exports.__defineGetter__(file, function () {
        return require('./' + file);
      });
    }
  });
```

**Comment by samsonjs** [comment]
Good idea, thanks!
